### PR TITLE
Fix SourceDistTask with underscore in version

### LINKED ISSUE #84: "setup.py sdist --dist-dir" command converts version numbers with `_` to `-`
This seems to be the opposite of what the `setup.py bdist_egg` command does.

When `setup.py sdist` encounters a version with an `_` character in it the resulting `tar.gz` file has the version converted to a `-`

So a version `'gradleBuild_2016111701.preview'`

Creates a `tar.gz` with the name: `$project.name-gradleBuild-2016111701.preview.tar.gz`

The `getSdistOutput` method in `SourceDistTask` should handle this.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
The project's version number, if it contains a `_` needs to be converted to a `-`.

Closes #84

### CODE REVIEW

File: pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/SourceDistTask.java [hunk 1]
```diff
@@ -35,7 +35,11 @@ public void processResults(ExecResult execResult) {
     @OutputFile
     public File getSdistOutput() {
         Project project = getProject();
-        return new File(getDistDir(), String.format("%s-%s.tar.gz", project.getName(), project.getVersion()));
+        return new File(getDistDir(),
```
Comment (zvezdan) [inline pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/SourceDistTask.java]: Can you break the line after the opening parenthesis, to have the parameters of `File()` aligned at the same indent level.

Comment (JLLeitschuh) [inline pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/SourceDistTask.java]: sure

**Comment by JLLeitschuh** [comment]
Is this good?
Do you need anything else??

**Comment by zvezdan** [comment]
Can you please rebase and squash commits?

**Comment by JLLeitschuh** [comment]
You can do this in the merge as an admin of this project.
Go to project settings and enable it.
https://github.com/blog/2141-squash-your-commits

**Comment by ethankhall** [comment]
Squashing commits removes history, and if we ever want to do some fixup before doing a merge (we've done this internally) you would loose credit for the commit on the merge commit. So we do merge commits for PR's.

**Comment by JLLeitschuh** [comment]
Oh, I didn't know that. Good to know for the future.
